# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'AzPipelines'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      docker: 'stable'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/simple_api/Dockerfile'
        tags: |
          $(tag)

- stage: Run
  displayName: run Containers
  jobs:  
  - job: run
    displayName: run
    pool:
      docker: 'stable'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
            - docker rm -vf student-list-api || echo "container already deleted"
            - docker run -d --name=student-list-api -p 5000:5000 gazambey/student-list-api:gitlab-ci
            - docker cp ${PWD}/simple_api/student_age.json student-list-api:/data/student_age.json


